### ISSUE TITLE
Fetching GHC HEAD: unable to download

### ISSUE THREAD

**Issue by nomeata** [mpickering/ghc-artefact-nix#15]
Following the README, I try
```
~/build/haskell/ghc $ nix run -f https://github.com/mpickering/ghc-artefact-nix/archive/master.tar.gz ghcHEAD
[0.0 MiB DL]
error: unable to download 'https://gitlab.haskell.org/ghc/ghc/-/jobs/artifacts/master/raw/ghc-x86_64-fedora27-linux.tar.xz?job=validate-x86_64-linux-fedora27': HTTP error 404
(use '--show-trace' to show detailed location information)
```
but it fails. Is this a bug, or a transient, expected failure? If the latter, maybe point that out in the README, including possible ways to work-around that, and get a recentish GHC.

**Comment by mpickering** [comment]
Yes this unfortunately has recently broken as the fedora27 job has become the fedora33 job.

**Comment by mpickering** [comment]
Fixed now.
