### ISSUE TITLE
Executable linking is broken

### ISSUE THREAD

**Issue by bgamari** [mpickering/ghc-artefact-nix#3]
@mpickering and I were discussing this on IRC: It seems that https://github.com/mpickering/ghc-artefact-nix/commit/633c6d7553d0f2c91245bcf47ae539cfdb7aaa13 is not sufficient to fix executable linking; there is still a dependency on `libtinfo` sneaking in somehow. I suspect this is via the package database.

**Comment by mpickering** [comment]
Fixed (apparently)
